In [11]:
!pip install matplotlib

Requirement already satisfied: matplotlib in ./.venv/lib/python3.14/site-packages (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.14/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.14/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in ./.venv/lib/python3.14/site-packages (from matplotlib) (2.4.2)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.14/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.14/site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in ./.venv/lib/python3.14/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.14/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [12]:
import pandas as pd
import matplotlib.pyplot as plt

In [13]:
df_Equipos = pd.read_csv("ordenes/ordenes_Equipos.csv")
df_Ordenes = pd.read_csv("ordenes/ordenes_Ordenes.csv")
df_Refacciones = pd.read_csv("ordenes/ordenes_Refacciones.csv")

In [14]:
# 220 Equipos

# 6 Marcas 'KENWORTH', 'INTERNATIONAL', 'MACK GRANITE', 'FOTON', 'SINOTRUCK', 'SCANIA'

# 16 anios de modelo 2000, 2005, 2006, 2007, 2008, 2013, 2014, 2015, 2016, 2017, 2019, 
# 2018, 2022, 2021, 2023, 2024

# 3 origenes de las unidades 'AMERICANO', 'CHINO', 'EUROPEO'

df_Equipos.rename(columns={'EQUIPO': 'equipo', 'MARCA': 'marca', 'MODELO': 'modelo', 'Unnamed: 3': 'origen'}, inplace=True)
df_Equipos

       equipo          marca  modelo     origen
0    30004229       KENWORTH    2000  AMERICANO
1    30004325  INTERNATIONAL    2005  AMERICANO
2    30004334  INTERNATIONAL    2006  AMERICANO
3    30004360       KENWORTH    2006  AMERICANO
4    30004363       KENWORTH    2006  AMERICANO
..        ...            ...     ...        ...
215  30013409      SINOTRUCK    2024      CHINO
216  30013410      SINOTRUCK    2024      CHINO
217  30013411      SINOTRUCK    2024      CHINO
218  30013412      SINOTRUCK    2024      CHINO
219  30013413      SINOTRUCK    2024      CHINO

[220 rows x 4 columns]

In [15]:
df_Equipos["origen"].value_counts(normalize=True).mul(100)

origen
AMERICANO    60.454545
CHINO        31.363636
EUROPEO       8.181818
Name: proportion, dtype: float64

In [16]:
df_Equipos["marca"].value_counts(normalize=True).mul(100)

marca
KENWORTH         34.090909
SINOTRUCK        29.090909
MACK GRANITE     17.272727
INTERNATIONAL     9.090909
SCANIA            8.181818
FOTON             2.272727
Name: proportion, dtype: float64

In [17]:
df_Equipos["modelo"].value_counts(normalize=True).mul(100)

modelo
2022    16.818182
2024    14.090909
2016    12.272727
2017    10.000000
2023     9.090909
2018     7.727273
2006     5.000000
2014     5.000000
2019     5.000000
2015     4.545455
2007     3.181818
2008     2.272727
2013     2.272727
2021     1.818182
2000     0.454545
2005     0.454545
Name: proportion, dtype: float64

In [18]:
import matplotlib.pyplot as plt
from PIL import Image

# Columns to visualize
columns = ["origen", "marca", "modelo"]

# Store temporary image paths
image_paths = []

for col in columns:
    plt.figure(figsize=(10, 6))
    
    # Create bar plot
    df_Equipos[col].value_counts().plot(kind="bar")
    
    # Improve formatting
    plt.title(f"Distribución por {col.capitalize()}", fontsize=16)
    plt.xlabel(col.capitalize(), fontsize=12)
    plt.ylabel("Frecuencia", fontsize=12)
    plt.xticks(rotation=45, ha="right")
    plt.grid(axis="y", linestyle="--", alpha=0.4)
    plt.tight_layout()
    
    # Save individual plot
    file_path = f"{col}_barplot.png"
    plt.savefig(file_path, dpi=300)
    plt.close()
    
    image_paths.append(file_path)

# Combine images vertically
images = [Image.open(p) for p in image_paths]

max_width = max(img.width for img in images)
total_height = sum(img.height for img in images)

combined_image = Image.new("RGB", (max_width, total_height))

y_offset = 0
for img in images:
    combined_image.paste(img, (0, y_offset))
    y_offset += img.height

# Save final combined image
final_path = "df_Equipos_barplots_combined.png"
combined_image.save(final_path)

print("Image saved as:", final_path)

Image saved as: df_Equipos_barplots_combined.png

In [19]:
# 668 ordenes inconclusas
# 32853 ordenes completadas

# 33521 ordenes totales
#print(df_Ordenes.isnull().sum())

df_Ordenes = df_Ordenes.rename(columns={
    'Description': 'description', 
    'Order': 'order', 
    'Created On': 'created_on',
    'Changed On': 'changed_on',
    'Equipment': 'equipment',
    'MaintPlant': 'main_plant',
    'Plant': 'plant'
})

df_Ordenes

,order,description,created_on,changed_on,equipment,main_plant,plant
0,41144642,TRABAJOS PHI,2020-01-03,2022-02-07,30004414,R592,R592
1,41144643,TRABAJOS PHI,2020-01-03,2022-02-07,30004415,R592,R592
2,41151313,TRABAJOS PHI,2020-01-24,2022-02-07,30004415,R592,R592
3,41152917,LLANTA RENOVADA 24.5,2020-01-29,2022-02-07,30004414,R592,R592
4,41154281,"BOMBA SUSTRAN, BABEROS Y FUGA DE AIRE",2020-02-04,2021-12-22,30004414,R592,R592
...,...,...,...,...,...,...,...
33516,41770249,ADL FEB CR6602,2026-02-20,NaN,30006602,R591,R591
33517,41770259,LLANTA 295 RENOV C-12512,2026-02-20,2026-02-20,30012512,R591,R591
33518,41770283,GAS FREON CR 5345,2026-02-20,NaN,30005345,R591,R591
33519,41770285,LIMPIEZA DE OLLA CR 12489,2026-02-20,NaN,30012489,R591,R591
33520,41479891,MP REVOLVEDORAS CONC CHIH 6163,2023-05-03,2023-09-17,30006163,R591,R592

In [20]:
df_Ordenes_null = df_Ordenes[df_Ordenes['changed_on'].isna()]
df_Ordenes_not_null = df_Ordenes[df_Ordenes['changed_on'].notna()]

In [21]:
# B4252
df_Equipos.loc[(df_Equipos['modelo'] == 2022) & (df_Equipos['marca'] == "SCANIA")]

       equipo   marca  modelo   origen
131  30011789  SCANIA    2022  EUROPEO
132  30011790  SCANIA    2022  EUROPEO
133  30011791  SCANIA    2022  EUROPEO
134  30011940  SCANIA    2022  EUROPEO
135  30011941  SCANIA    2022  EUROPEO
157  30012484  SCANIA    2022  EUROPEO
158  30012485  SCANIA    2022  EUROPEO
159  30012486  SCANIA    2022  EUROPEO
160  30012487  SCANIA    2022  EUROPEO
161  30012488  SCANIA    2022  EUROPEO
162  30012489  SCANIA    2022  EUROPEO
163  30012511  SCANIA    2022  EUROPEO
164  30012512  SCANIA    2022  EUROPEO
165  30012513  SCANIA    2022  EUROPEO
166  30012514  SCANIA    2022  EUROPEO
167  30012515  SCANIA    2022  EUROPEO
168  30012516  SCANIA    2022  EUROPEO

In [22]:
#df_Refacciones
#df.isnull().sum()
#df_Refacciones.isnull().sum()
#df_Refacciones.count()
df_Refacciones = df_Refacciones.rename(columns={
    "Order":"order",
    "Description": "description",
    "G/L Account": "g_l_account",
    "Material Doc.": "material_doc",
    "Document Date": "document_date",
    "Material": "material",
    "Quantity": "quantity",
    "Posting Date": "posting_date",
    "Quantity in UnE": "quantity_in_une",
    "Vendor": "vendor"
})
df_Refacciones

,order,description,g_l_account,material_doc,document_date,material,quantity,posting_date,quantity_in_une,vendor
0,41144769,FILTRO ZFGLF680,440301.0,4914260344,2020-01-06,1066303.0,1.0,2020-01-06,1.0,608994.0
1,41144769,VACUOMETRO 260-00422,440301.0,4914260344,2020-01-06,1073418.0,1.0,2020-01-06,1.0,609172.0
2,41144769,RODAMIENTO P/OLLA 220-1504440,440301.0,4914260344,2020-01-06,1071683.0,1.0,2020-01-06,1.0,609172.0
3,41144694,LLANTA RENOVADA 11R24.5TRA VM530L,440306.0,4914262052,2020-01-06,1097649.0,1.0,2020-01-06,1.0,613507.0
4,41144766,ACEITE MOBIL DTE 26 19LT,440322.0,4914262052,2020-01-06,3000791.0,38.0,2020-01-06,38.0,608775.0
...,...,...,...,...,...,...,...,...,...,...
104407,41769152,LAINA EGR,440301.0,5008411198,2026-02-20,NaN,0.0,2026-02-20,2.0,619848.0
104408,41769152,LIGAS TUBO TURBO,440301.0,5008411198,2026-02-20,NaN,0.0,2026-02-20,3.0,619848.0
104409,41769152,TUBO,440301.0,5008411198,2026-02-20,NaN,0.0,2026-02-20,1.0,619848.0
104410,41769152,EMPAQUE TURBO,440301.0,5008411198,2026-02-20,NaN,0.0,2026-02-20,1.0,619848.0
104411,41769152,GANCHO DE COFRE,440301.0,5008411198,2026-02-20,NaN,0.0,2026-02-20,1.0,619848.0

In [23]:
df_Ordenes_not_null.loc[df_Ordenes["equipment"] == 30006602]

,order,description,created_on,changed_on,equipment,main_plant,plant
18274,41146346,SERVICIO HIDRAULICO CAMION 6602,2020-01-09,2022-07-02,30006602,R591,R591
18289,41148479,Cambio de marcha de canalon C6602,2020-01-15,2022-07-02,30006602,R591,R591
18335,41154557,CAMBIO DE BALATAS TRACERAS C 6609,2020-02-04,2022-07-02,30006602,R591,R591
18347,41156563,CAMBIO DE PILAS UNIDAD 6602,2020-02-11,2022-07-02,30006602,R591,R591
18417,41170937,CAMBIO DE BALATAS PARA 6602,2020-04-03,2022-07-02,30006602,R591,R591
...,...,...,...,...,...,...,...
32897,41757970,REEMPLAZO BUJE PARED DE FUEGO CR 6602,2026-01-07,2026-02-17,30006602,R591,R591
33160,41762328,RODAMIENTO CR 6602,2026-01-23,2026-02-17,30006602,R591,R591
33177,41763329,REEMPLAZO DE MUELLE CR 6602,2026-01-27,2026-02-16,30006602,R591,R591
33403,41767543,ADL FEBRERO 2026 CR 6602,2026-02-11,2026-02-17,30006602,R591,R591
33425,41767807,DESTELLADOR TRIDON CR 6602,2026-02-11,2026-02-17,30006602,R591,R591

In [24]:
df_Refacciones.loc[df_Refacciones["description"].str.contains('fs', case=False) ]["description"].unique()

<StringArray>
[                         'FILTRO FS-19624',
                 'FILTRO RE522878/FS-19976',
                           'FILTRO FS-1000',
                 'CAJA ELECTRICA FS 3/4PUL',
          'FLRTFS1000 FLT FILTRO SEPARADOR',
 'REFACCIONES EQUIPO MOVIL - FLRTFS19624 F',
 'REFACCIONES EQUIPO MOVIL - FLRTFS1000 FL',
 'REFACCIONES EQUIPO MOVIL - ZFGFS1000 FLE',
 'TERMINAL DE DIRECCION LH EJE MFS20 = A31',
 'TERMINAL DE DIRECCION RH EJE MFS20 = A31',
                 'FILTRO SEPARADOR FS19624',
            'FILTRO COMBUSTIBLE  FS1000FLG',
             'FILTRO COMBUSTIBLE FS1000FLG',
            'ESPEJO CONVEXO OFFSET MNT 8.5',
 'FS1029WFLG FILTRO COMBUSTIBLE FLEETGUARD',
            'DIAGNOSTICO DE UNIDADES (IFS)',
 'JGO DE PERNOS EJE DEL MARITOR MFS20 3101',
                 'CAJA ELECTRICA FS 1/2PUL',
               'FILTRO COMBUSTIBLE FS20203',
                 'FILTRO SEPARADOR FS-1098',
                'FS53016\tFILTRO SEPARADOR',
       '"FILTRO DIESEL 53C0051, FS1280 - 4',
 'TERMINAL DE DIRECCION LH EJE MFS20 =  A3',
 'TERMINAL DE DIRECCION RH EJE MFS20 =  A3']
Length: 24, dtype: str

In [25]:
#merged = df_Ordenes_not_null.join(df_Equipos.set_index('equipo'), on='equipo', how='inner')
#merged
df_Equipos = df_Equipos.rename(columns={"equipo": "equipment"})

merged = df_Ordenes_not_null.merge(
    df_Equipos,
    on="equipment",
    how="inner"
)

merged
merged.to_csv("consolidated_ordenes.csv", index=False)

In [26]:
merged = merged.drop(columns=["description"])
merged = merged.merge(
    df_Refacciones,
    on="order",
    how="left"
)

merged

,order,created_on,changed_on,equipment,main_plant,plant,marca,modelo,origen,description,g_l_account,material_doc,document_date,material,quantity,posting_date,quantity_in_une,vendor
0,41144642,2020-01-03,2022-02-07,30004414,R592,R592,INTERNATIONAL,2007,AMERICANO,SERVICIO DE MANTENIMIENTO A OLLAS TALLER,440303.0,5.005184e+09,2020-01-03,NaN,0.0,2020-01-03,1.0,609536.0
1,41144642,2020-01-03,2022-02-07,30004414,R592,R592,INTERNATIONAL,2007,AMERICANO,SERVICIO DE MANTENIMIENTO A OLLAS TALLER,440303.0,5.005184e+09,2020-01-03,NaN,0.0,2020-01-03,1.0,609536.0
2,41144642,2020-01-03,2022-02-07,30004414,R592,R592,INTERNATIONAL,2007,AMERICANO,SERVICIO DE MANTENIMIENTO A OLLAS TALLER,440303.0,5.005184e+09,2020-01-03,NaN,0.0,2020-01-03,1.0,609536.0
3,41144642,2020-01-03,2022-02-07,30004414,R592,R592,INTERNATIONAL,2007,AMERICANO,SERVICIO DE MANTENIMIENTO A OLLAS TALLER,440303.0,5.005184e+09,2020-01-03,NaN,0.0,2020-01-03,1.0,609536.0
4,41144642,2020-01-03,2022-02-07,30004414,R592,R592,INTERNATIONAL,2007,AMERICANO,SERVICIO DE MANTENIMIENTO A OLLAS TALLER,440303.0,5.005184e+09,2020-01-03,NaN,0.0,2020-01-03,1.0,609536.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106772,41769532,2026-02-18,2026-02-18,30007042,R591,R591,MACK GRANITE,2017,AMERICANO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106773,41769534,2026-02-18,2026-02-18,30012227,R591,R591,SINOTRUCK,2022,CHINO,LLANTA 385/65 R22.5 AM15,440306.0,4.924940e+09,2026-02-18,1101860.0,1.0,2026-02-18,1.0,619126.0
106774,41769947,2026-02-19,2026-02-19,30012488,R591,R591,SCANIA,2022,EUROPEO,LLANTA RENOVADA 295/75R22.5TRA,440306.0,4.924948e+09,2026-02-19,1105967.0,2.0,2026-02-19,2.0,619126.0
106775,41770259,2026-02-20,2026-02-20,30012512,R591,R591,SCANIA,2022,EUROPEO,LLANTA RENOVADA 295/75R22.5TRA,440306.0,4.924953e+09,2026-02-20,1105967.0,1.0,2026-02-20,1.0,619126.0
106776,41479891,2023-05-03,2023-09-17,30006163,R591,R592,KENWORTH,2015,AMERICANO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
merged = merged.drop(columns=[
    "description",
    "main_plant",
    "g_l_account",
    "material_doc",
    "document_date",
    "material",
    "posting_date",
    "vendor",
    "quantity_in_une"
])

merged

,order,created_on,changed_on,equipment,plant,marca,modelo,origen,quantity
0,41144642,2020-01-03,2022-02-07,30004414,R592,INTERNATIONAL,2007,AMERICANO,0.0
1,41144642,2020-01-03,2022-02-07,30004414,R592,INTERNATIONAL,2007,AMERICANO,0.0
2,41144642,2020-01-03,2022-02-07,30004414,R592,INTERNATIONAL,2007,AMERICANO,0.0
3,41144642,2020-01-03,2022-02-07,30004414,R592,INTERNATIONAL,2007,AMERICANO,0.0
4,41144642,2020-01-03,2022-02-07,30004414,R592,INTERNATIONAL,2007,AMERICANO,0.0
...,...,...,...,...,...,...,...,...,...
106772,41769532,2026-02-18,2026-02-18,30007042,R591,MACK GRANITE,2017,AMERICANO,NaN
106773,41769534,2026-02-18,2026-02-18,30012227,R591,SINOTRUCK,2022,CHINO,1.0
106774,41769947,2026-02-19,2026-02-19,30012488,R591,SCANIA,2022,EUROPEO,2.0
106775,41770259,2026-02-20,2026-02-20,30012512,R591,SCANIA,2022,EUROPEO,1.0
106776,41479891,2023-05-03,2023-09-17,30006163,R592,KENWORTH,2015,AMERICANO,NaN

In [28]:
merged = merged.rename(columns={
    "quantity": "replacement_quantity",
    "equipment": "equipment_id",
    "marca": "equipment_brand",
    "modelo": "equipment_model",
    "origen": "equipment_origin",
})

merged

,order,created_on,changed_on,equipment_id,plant,equipment_brand,equipment_model,equipment_origin,replacement_quantity
0,41144642,2020-01-03,2022-02-07,30004414,R592,INTERNATIONAL,2007,AMERICANO,0.0
1,41144642,2020-01-03,2022-02-07,30004414,R592,INTERNATIONAL,2007,AMERICANO,0.0
2,41144642,2020-01-03,2022-02-07,30004414,R592,INTERNATIONAL,2007,AMERICANO,0.0
3,41144642,2020-01-03,2022-02-07,30004414,R592,INTERNATIONAL,2007,AMERICANO,0.0
4,41144642,2020-01-03,2022-02-07,30004414,R592,INTERNATIONAL,2007,AMERICANO,0.0
...,...,...,...,...,...,...,...,...,...
106772,41769532,2026-02-18,2026-02-18,30007042,R591,MACK GRANITE,2017,AMERICANO,NaN
106773,41769534,2026-02-18,2026-02-18,30012227,R591,SINOTRUCK,2022,CHINO,1.0
106774,41769947,2026-02-19,2026-02-19,30012488,R591,SCANIA,2022,EUROPEO,2.0
106775,41770259,2026-02-20,2026-02-20,30012512,R591,SCANIA,2022,EUROPEO,1.0
106776,41479891,2023-05-03,2023-09-17,30006163,R592,KENWORTH,2015,AMERICANO,NaN

In [29]:
orders_by_features = (
    merged
    .groupby([
        "plant",
        "equipment_brand",
        "equipment_model",
        "equipment_origin"
    ])["order"]
    .count()
    .reset_index(name="order_count")
)

orders_by_features

   plant equipment_brand  equipment_model equipment_origin  order_count
0   R591           FOTON             2021            CHINO          407
1   R591           FOTON             2023            CHINO         1252
2   R591   INTERNATIONAL             2005        AMERICANO          269
3   R591   INTERNATIONAL             2006        AMERICANO         1243
4   R591   INTERNATIONAL             2007        AMERICANO          451
5   R591   INTERNATIONAL             2008        AMERICANO          471
6   R591   INTERNATIONAL             2015        AMERICANO          678
7   R591   INTERNATIONAL             2016        AMERICANO          792
8   R591        KENWORTH             2006        AMERICANO          846
9   R591        KENWORTH             2007        AMERICANO          310
10  R591        KENWORTH             2008        AMERICANO          681
11  R591        KENWORTH             2013        AMERICANO         2940
12  R591        KENWORTH             2014        AMERICANO           64
13  R591        KENWORTH             2015        AMERICANO         2273
14  R591        KENWORTH             2016        AMERICANO         8077
15  R591        KENWORTH             2017        AMERICANO          704
16  R591        KENWORTH             2018        AMERICANO         2450
17  R591        KENWORTH             2023        AMERICANO          734
18  R591    MACK GRANITE             2016        AMERICANO          616
19  R591    MACK GRANITE             2017        AMERICANO         5486
20  R591    MACK GRANITE             2018        AMERICANO         1529
21  R591    MACK GRANITE             2019        AMERICANO         5695
22  R591    MACK GRANITE             2022        AMERICANO          515
23  R591          SCANIA             2021          EUROPEO          432
24  R591          SCANIA             2022          EUROPEO         6046
25  R591       SINOTRUCK             2021            CHINO          730
26  R591       SINOTRUCK             2022            CHINO         6118
27  R591       SINOTRUCK             2023            CHINO         1109
28  R591       SINOTRUCK             2024            CHINO          691
29  R592           FOTON             2023            CHINO            9
30  R592   INTERNATIONAL             2005        AMERICANO          342
31  R592   INTERNATIONAL             2006        AMERICANO         1586
32  R592   INTERNATIONAL             2007        AMERICANO         2016
33  R592   INTERNATIONAL             2008        AMERICANO         1895
34  R592   INTERNATIONAL             2015        AMERICANO          736
35  R592   INTERNATIONAL             2023        AMERICANO          463
36  R592   INTERNATIONAL             2024        AMERICANO          200
37  R592        KENWORTH             2000        AMERICANO          304
38  R592        KENWORTH             2006        AMERICANO         4204
39  R592        KENWORTH             2007        AMERICANO         1605
40  R592        KENWORTH             2008        AMERICANO          869
41  R592        KENWORTH             2013        AMERICANO          586
42  R592        KENWORTH             2014        AMERICANO         7006
43  R592        KENWORTH             2015        AMERICANO         3137
44  R592        KENWORTH             2016        AMERICANO         6865
45  R592        KENWORTH             2017        AMERICANO         4928
46  R592        KENWORTH             2018        AMERICANO         1350
47  R592        KENWORTH             2022        AMERICANO          709
48  R592    MACK GRANITE             2014        AMERICANO          559
49  R592    MACK GRANITE             2016        AMERICANO          943
50  R592    MACK GRANITE             2017        AMERICANO         2827
51  R592    MACK GRANITE             2018        AMERICANO         3699
52  R592    MACK GRANITE             2019        AMERICANO          692
53  R592       SINOTRUCK             2018            CHINO          380
54  R592       SINOTRUCK             2022            CHINO           50
55  R592       SINOTRUCK             2023            CHINO          911
56  R592       SINOTRUCK             2024            CHINO         4297

In [30]:
orders_by_features["percentage"] = (
    orders_by_features["order_count"]
    / orders_by_features["order_count"].sum()
    * 100
)

orders_by_features

,plant,equipment_brand,equipment_model,equipment_origin,order_count,percentage
0,R591,FOTON,2021,CHINO,407,0.381168
1,R591,FOTON,2023,CHINO,1252,1.172537
2,R591,INTERNATIONAL,2005,AMERICANO,269,0.251927
3,R591,INTERNATIONAL,2006,AMERICANO,1243,1.164108
4,R591,INTERNATIONAL,2007,AMERICANO,451,0.422376
5,R591,INTERNATIONAL,2008,AMERICANO,471,0.441106
6,R591,INTERNATIONAL,2015,AMERICANO,678,0.634968
7,R591,INTERNATIONAL,2016,AMERICANO,792,0.741733
8,R591,KENWORTH,2006,AMERICANO,846,0.792305
9,R591,KENWORTH,2007,AMERICANO,310,0.290325
10,R591,KENWORTH,2008,AMERICANO,681,0.637778
11,R591,KENWORTH,2013,AMERICANO,2940,2.753402
12,R591,KENWORTH,2014,AMERICANO,64,0.059938
13,R591,KENWORTH,2015,AMERICANO,2273,2.128736
14,R591,KENWORTH,2016,AMERICANO,8077,7.564363
15,R591,KENWORTH,2017,AMERICANO,704,0.659318
16,R591,KENWORTH,2018,AMERICANO,2450,2.294502
17,R591,KENWORTH,2023,AMERICANO,734,0.687414
18,R591,MACK GRANITE,2016,AMERICANO,616,0.576903
19,R591,MACK GRANITE,2017,AMERICANO,5486,5.137811
20,R591,MACK GRANITE,2018,AMERICANO,1529,1.431956
21,R591,MACK GRANITE,2019,AMERICANO,5695,5.333546
22,R591,MACK GRANITE,2022,AMERICANO,515,0.482314
23,R591,SCANIA,2021,EUROPEO,432,0.404582
24,R591,SCANIA,2022,EUROPEO,6046,5.662268
25,R591,SINOTRUCK,2021,CHINO,730,0.683668
26,R591,SINOTRUCK,2022,CHINO,6118,5.729698
27,R591,SINOTRUCK,2023,CHINO,1109,1.038613
28,R591,SINOTRUCK,2024,CHINO,691,0.647143
29,R592,FOTON,2023,CHINO,9,0.008429
30,R592,INTERNATIONAL,2005,AMERICANO,342,0.320294
31,R592,INTERNATIONAL,2006,AMERICANO,1586,1.485339
32,R592,INTERNATIONAL,2007,AMERICANO,2016,1.888047
33,R592,INTERNATIONAL,2008,AMERICANO,1895,1.774727
34,R592,INTERNATIONAL,2015,AMERICANO,736,0.689287
35,R592,INTERNATIONAL,2023,AMERICANO,463,0.433614
36,R592,INTERNATIONAL,2024,AMERICANO,200,0.187306
37,R592,KENWORTH,2000,AMERICANO,304,0.284706
38,R592,KENWORTH,2006,AMERICANO,4204,3.937177
39,R592,KENWORTH,2007,AMERICANO,1605,1.503133
40,R592,KENWORTH,2008,AMERICANO,869,0.813846
41,R592,KENWORTH,2013,AMERICANO,586,0.548807
42,R592,KENWORTH,2014,AMERICANO,7006,6.561338
43,R592,KENWORTH,2015,AMERICANO,3137,2.937899
44,R592,KENWORTH,2016,AMERICANO,6865,6.429287
45,R592,KENWORTH,2017,AMERICANO,4928,4.615226
46,R592,KENWORTH,2018,AMERICANO,1350,1.264317
47,R592,KENWORTH,2022,AMERICANO,709,0.664001
48,R592,MACK GRANITE,2014,AMERICANO,559,0.523521
49,R592,MACK GRANITE,2016,AMERICANO,943,0.883149
50,R592,MACK GRANITE,2017,AMERICANO,2827,2.647574
51,R592,MACK GRANITE,2018,AMERICANO,3699,3.464229
52,R592,MACK GRANITE,2019,AMERICANO,692,0.648080
53,R592,SINOTRUCK,2018,CHINO,380,0.355882
54,R592,SINOTRUCK,2022,CHINO,50,0.046827
55,R592,SINOTRUCK,2023,CHINO,911,0.853180
56,R592,SINOTRUCK,2024,CHINO,4297,4.024275

In [33]:
brand_stats = (
    orders_by_features
    .groupby("equipment_brand")["order_count"]
    .sum()
    .describe()
)

brand_totals = (
    orders_by_features
    .groupby("equipment_brand")["order_count"]
    .sum()
    .sort_values(ascending=False)
)

brand_stats
brand_totals

equipment_brand
KENWORTH         50642
MACK GRANITE     22561
SINOTRUCK        14286
INTERNATIONAL    11142
SCANIA            6478
FOTON             1668
Name: order_count, dtype: int64